In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
train = ["ram ram is a good boy"]

In [3]:
vectorizer = TfidfVectorizer(lowercase=True)

In [4]:
vectorizer.fit(train)

TfidfVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm=u'l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern=u'(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [9]:
vectorizer.transform(["ram good boy"]).todense()

matrix([[ 0.57735027,  0.57735027,  0.        ,  0.57735027]])

In [ ]:
So it is 1/sq.rt(3) for each of them since it is L2 norm

In [6]:
vectorizer.transform(["ram good train"]).todense()

matrix([[ 0.        ,  0.70710678,  0.        ,  0.70710678]])

In [7]:
vectorizer.transform(["is"]).todense()

matrix([[ 0.,  0.,  1.,  0.]])

In [8]:
vectorizer._tfidf.idf_

array([ 1.,  1.,  1.,  1.])